### ISSUE TITLE
Bananas re-starting file-upload when uploading an update

### ISSUE THREAD

**Issue by GarlicBread42** [OpenTTD/bananas-frontend-web#227]
Currently BaNaNas loops file uploads when trying to update existing .grf's in the database.

After ticking the Terms of Service box and uploading the file, the upload starts. Once the upload hits 100%, it takes a short break and re-starts from 0%. 

The issue occurs with latest Firefox and Edge browsers. The .grf has been compiled twice and uploaded. Also occurs when the .grf is packed into a zip-file before.

**Comment by TrueBrain** [comment]
There are no errors in the backend, and when I try it with Firefox it works fine. So this needs a bit further investigation.

@frosch123 Do you happen to have some time to check this out? I guess we need a way to reproduce, or get those browser console logs / network logs?

**Comment by GarlicBread42** [comment]
[console-export-2023-10-3_21-50-28.txt](https://github.com/OpenTTD/bananas-frontend-web/files/12796547/console-export-2023-10-3_21-50-28.txt)

I've just re-tried to upload, you'll find the browser console logs attached. If you need anything else, please let me know.

**Comment by frosch123** [comment]
I can reproduce the error with a larger upload:
* 20MB works.
* 313MB fails with error 413 "request entity too large".
